### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by spors**

### CODE REVIEW

**Comment by spors** [comment]
Revised implementation of animation to use symbolic functions directly.

**Comment by fs446** [comment]
Very nice!!
I've just added small corrections in 933e84371f523786d2155fde3c1d6db557bd277a and would be ok to merge this for now.
Handling of axis limits, ticks with animate_convolution() keywords should be improved in future.

**Comment by spors** [comment]
I have modified the implementation of the convolution animation to use SymPy plotting primitives together with matplotlib collections.

**Review by mgeier — COMMENTED** [review]
```
$ python3 -m pycodestyle systems_time_domain/animation.py 
systems_time_domain/animation.py:34:80: E501 line too long (90 > 79 characters)
systems_time_domain/animation.py:40:80: E501 line too long (82 > 79 characters)
$ python3 -m pydocstyle systems_time_domain/animation.py 
systems_time_domain/animation.py:1 at module level:
        D100: Missing docstring in public module
systems_time_domain/animation.py:8 in public function `animate_convolution`:
        D205: 1 blank line required between summary line and description (found 0)
systems_time_domain/animation.py:8 in public function `animate_convolution`:
        D413: Missing blank line after last section ('Returns')
```

**Comment by spors** [comment]
Merged into master

**Pull request merged**
